### ISSUE TITLE
Configuring Git and GitHub on WSL2

### ISSUE THREAD

**Issue by Aking8089** [learn-co-curriculum/phase-0-wsl2-env-verification-py#1]
### Canvas Link

https://learning.flatironschool.com/courses/6611/pages/configuring-git-and-github-on-wsl2?module_item_id=52543

### Concern

I am having a issue with downloading 4 of the apps thats not installed is says 4 not upgraded. When I move on to the next page it says I am missing the 4 need to be downloaded in the pass window. They are missing in that pass window the rest are there except the 4.

**Comment by lizbur10** [comment]
Thanks for raising this issue. Based on your description, it sounds like the
issue may be related to your environment setup rather than with the lesson
itself or the instructions. The curriculum team monitors these issues so that we
can fix typos and bugs in the curriculum, but we aren't equipped to provide
support.

To get help with your question, you should either:

- Reach out to your instructor (if you've started the program and have an
  instructor)
- Use the
  [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit)
  feature in Canvas to connect with a Technical Coach on the Academic Success
  Team

Please re-open this issue if you believe the lesson needs to be updated.

Hope you are able to get this resolved!
